---
title: "Reticulate"
output: html_document
date: "2024-12-27"
---

```{r}
# Necesitamos intalar mhn en el contenedor. Para ello, 
## cmd de windows --> docker ps --> coger container ID
## docker exec -it <container_ID> bash
## verificar que python esta instalado --> python --version
## Si no esta instalado: 
## apt-get update
## apt-get install python3 python3-pip -y
## Verificar que ahora si esta instalado: python3 --version (a mi me sale Python 3.10.12)
## Ahora si podemos configurar reticulate

```

## Instalar y cargar reticulate en R

```{r}
# # Instalar 'reticulate' si no está instalado
# install.packages("reticulate")

# Cargar el paquete 'reticulate'
library(reticulate)

```

```{r}
##Escribir en cmd pip3 install mhn para instalar el paquete mhn en el contenedor
## Verificar que se ha intalado de forma correcta: 
## python3 -c "import mhn; print(mhn.__version__)"
## Deberia devolver 1.0.0
```


```{r}
# Configurar reticulate para usar Python 3
use_python("/usr/bin/python3", required = TRUE)

# Verificar la configuración de Python
py_config()

```

```{r}
# Usar mhn desde RStudio
mhn <- import("mhn")

# Usar reticulate para obtener el atributo __version__ del paquete mhn
mhn_version <- py_get_attr(mhn, "__version__")

# Imprimir la versión
print(mhn_version)
```


```{r}
# Verificar que se está utilizando el entorno correcto de Python
py_config()

# # Instalar el paquete 'mhn' usando pip (desde RStudio)
# py_run_string("!pip install mhn")
# 
# mhn <- import("mhn")

```


```{r}
# Cargar el archivo CSV en un dataframe en R
data <- read.csv('LUAD_n12.csv')

# Asegurarse de que los datos se carguen correctamente
head(data)


# Ejecutar las funciones de Python usando reticulate
py_run_string("from mhn.optimizers import oMHNOptimizer, cMHNOptimizer")
py_run_string("cMHN_opt = cMHNOptimizer()")
py_run_string("oMHN_opt = oMHNOptimizer()")

# Convertir el dataframe de R a un dataframe de pandas en Python
py$data <- r_to_py(data)  # Convertir el dataframe de R a Python

# Cargar los datos en los optimizadores
py_run_string("cMHN_opt.load_data_matrix(data)")
py_run_string("oMHN_opt.load_data_matrix(data)")

# Establecer las penalizaciones para cMHN y oMHN
py_run_string("cMHN_opt.set_penalty(cMHN_opt.Penalty.L1)")
py_run_string("oMHN_opt.set_penalty(oMHN_opt.Penalty.SYM_SPARSE)")

# Verificar si se cargaron correctamente los datos y la configuración
py_run_string("print(cMHN_opt)")
py_run_string("print(oMHN_opt)")

```
```{r}



```

